language: node_js
node_js: '9'
dist: trusty
sudo: required
cache:
  directories:
  - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_7e6eeb2896bb_key -iv $encrypted_7e6eeb2896bb_iv
  -in deploy_rsa.enc -out deploy_rsa -d
before_script:
- npm install -g @angular/cli
- npm install -g surge
- node git.version.js
script:
- npm install
- npm run build
addons:
  ssh_known_hosts: water-fountains.org
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@water-fountains.org:/var/www/stable
  on:
    branch: stable
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@water-fountains.org:/var/www/snapshot/${TRAVIS_COMMIT::7}
  on:
    all_branches: true
- provider: surge
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != stable"
  project: "./dist"
  domain: wf-${TRAVIS_COMMIT::7}.surge.sh
