language: node_js
node_js: "9"
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
before_install:
  # we only need the certificate for deployment, thus we don't install it if:
  # - we are on a fork (i.e. not water-fountains/proximap) or
  # - not on branch stable or develop (i.e. we are on a feature branch)
  - |
    if [[ "$TRAVIS_REPO_SLUG" == "water-fountains/proximap" && "$TRAVIS_EVENT_TYPE" == "push" && ("$TRAVIS_BRANCH" == stable || "$TRAVIS_BRANCH" == develop) ]]; then
      openssl aes-256-cbc -K $encrypted_e64b3d07f71e_key -iv $encrypted_e64b3d07f71e_iv \
        -in deploy_rsa.enc -out deploy_rsa -d;
      chmod 400 deploy_rsa;
    fi
before_script:
  - npm install -g @angular/cli
  - npm run prestart
script:
  - npm install
  - npm run sync_datablue
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script:
      rsync -e "ssh -i deploy_rsa -o StrictHostKeyChecking=no" -r --delete-after
      --quiet $TRAVIS_BUILD_DIR/dist/. root@water-fountains.org:/var/www/stable
    on:
      branch: stable
  - provider: script
    skip_cleanup: true
    script:
      rsync -e "ssh -i deploy_rsa -o StrictHostKeyChecking=no" -r $TRAVIS_BUILD_DIR/dist/.
      root@water-fountains.org:/var/www/beta/code/dist
    on:
      branch: develop
notifications:
  slack:
    secure: ZfblmbbAKvZvUFNuMIara2kHBLlhjCpxiK6pc+YtXFvwrgNkWni26MP/mcIsQC+ABXntMrR6W6u9OER286YoOlblIjRVOrI3quSkfPQj5joLE/LJBe01cwd8aLy0HqpD+y3F/CD+2Oym+fpSns6zFEhHhpLPyoTTMl7Irb90IMswTAhfDW4KbLl8reJq4juShR5VirVxA4d+zG9yQMyM98tPQfQc5tvQA2U5nqjxie+53R60b2TR6FGEBkvNgm+s/h1r+kr8CdtX1UBOBqJ9e+UrX3/2btgPoWUgijtqp6n+9W4oDwdr4UmlM2BJ1l2QwwXydp4J9qsiK7ncboiECVr/OtMqxTKddLKdUzp0HFufv3Ve1MhTY7C8b9RSqjmsJuwYHCyPzwj0Smv0Gdm9SqJ0cvBy4k+mYa0K+5CWrP0WIDBT0FKDhRaHNkmIm6QfRGhqXSBWCTdPJXtJOkmID2cQroSEAyYLs+PfW/YGLX82O+vx4Y8pWfB85SASh1zVvuYD7PrWC/tbsVlIpXxwIhCbP96U/jp3I9KO0q4a9V+OX8IpJ3Dr3iuImGoFOtq/sqyE8fbrq56Bgx5cNsopFLCfc/P3codzn8ZdsBY9ZnGMS90Z/BRlUDs7Qs/Uv3GFhYzKUDHvJm01lEF5bAOJgCsq+UHveoBKFjn2rnV66mk=
