language: node_js
node_js: '9'
dist: trusty
sudo: required
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_4b939a2144fc_key -iv $encrypted_4b939a2144fc_iv -in deploy_rsa.enc -out id_rsa -d
- ls -lart
before_script:
- npm install -g @angular/cli
- npm install -g surge
- node git.version.js
script:
- npm install
- npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -e "ssh -o StrictHostKeyChecking=no" -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@water-fountains.org:/var/www/stable
  on:
    branch: stable
    
- provider: script
  skip_cleanup: true
  script: scp -o StrictHostKeyChecking=no -r $TRAVIS_BUILD_DIR/dist/. root@water-fountains.org:/var/www/beta/code/dist
  on:
    branch: develop
    
- provider: script
  skip_cleanup: true
  script: rsync -e "ssh -o StrictHostKeyChecking=no" -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@water-fountains.org:/var/www/snapshot/${TRAVIS_COMMIT::7}
  on:
    branch: none
    
- provider: surge
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != stable"
  project: "./dist"
  domain: wf-${TRAVIS_COMMIT::7}.surge.sh
