language: node_js
node_js: '9'
dist: trusty
sudo: required
before_script:
- npm install -g @angular/cli
- npm install -g surge
- node git.version.js
script:
- npm ci
- ng build --prod

addons:
  ssh_known_hosts: water-fountains.org

before_deploy:
- openssl aes-256-cbc -K $encrypted_1b6af301316f_key -iv $encrypted_1b6af301316f_iv
  -in deploy_rsa.enc -out deploy_rsa -d

deploy:
  - provider: surge
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != stable
    project: "./dist"
    domain: wf-${TRAVIS_COMMIT::7}.surge.sh
    # deploy to server stable
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@water-fountains.org:/var/www/stable
    on:
      branch: stable
    # deploy to snapshots
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@water-fountains.org:/var/www/snapshot/${TRAVIS_COMMIT::7}
    on:
      all_branches: true
