language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - stable
before_script:
  - npm install -g @angular/cli
  - npm install -g surge
  - node git.version.js
script:
- npm ci
- ng build --prod
deploy:
  provider: surge
  project: ./dist
  domain: wf-travis-test.surge.sh
