name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "9"
      - run: npm install -g @angular/cli
      - run: npm install
      - name: check
        run: |
          set -e
          npm run prestart
          npm run sync_datablue
          npm run build
      - name: setup SSH
        if: ${{ github.repository == 'water-fountains/proximap' && github.event_name == 'push' && (github.ref == 'refs/heads/stable' ||  github.ref == 'refs/heads/test-deploy') }}
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH }}
          SSH_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "$SSH_PRIVATE_KEY"
      - name: deploy.develop
        if: ${{ github.repository == 'water-fountains/proximap' && github.event_name == 'push' && (github.ref == 'refs/heads/stable' ||  github.ref == 'refs/heads/test-deploy') }}
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          current_dir="$(pwd)"
          if [ "${{ github.ref }}" == "refs/heads/stable" ]; then
            rsync -r --delete-after --quiet "$current_dir/dist/." deploy@water-fountains.org:/var/www/stable
          else
            rsync -r $current_dir/dist/. deploy@water-fountains.org:/var/www/beta/code/dist
          fi
      - name: Cleanup ssh
        if: always()
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-add -D
          rm -Rf *
